### ISSUE TITLE
ir unexpectedly targets binary formats

### ISSUE THREAD

**Issue by kachick** [kachick/dotfiles#907]
https://github.com/kachick/dotfiles/blob/0b86d5a873bc9aa96c27c7f84531c236169767b4/pkgs/ir/ir.bash#L1-L10

it replaced a png

```
/tmp/tmp.L5BwQT836S.rb:1:in `gsub!': invalid byte sequence in UTF-8 (ArgumentError)
        from /tmp/tmp.L5BwQT836S.rb:1:in `<main>'
```

**Comment by kachick** [comment]
https://github.com/sharkdp/fd/issues/749

**Comment by kachick** [comment]
* I don't wish to add the handlings in ruby
* Pipe with file command will not fit with --exec-batch in fd

So filtering with file and classically use of xargs might be better?

**Comment by kachick** [comment]
https://github.com/zevweiss/grep/commit/c5b5567e5d265cb8d7171e7d2add249bfefbf685

**Comment by kachick** [comment]
```console
> fd --type file --hidden --exclude .git | xargs grep --binary-files=without-match -l --fixed-strings -e '' | xargs ruby -e 'p ARGV.length'
129
```
